extends: relaxed

rules:
  line-length:
    max: 120
  indentation:
    spaces: 2
  key-duplicates: enable
  # Allow docker-compose specific patterns
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
