global:
  # Default SMTP configuration
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@jira2solidtime.local'

# Template files for custom message formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing tree for alerts
route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 24h
  receiver: 'default-notifications'

  routes:
    # Critical alerts - immediate notification to both channels
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 5m

    # Warning alerts - less frequent notifications
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 2m
      repeat_interval: 2h

# Notification receivers
receivers:
  - name: 'default-notifications'
    # Fallback receiver for uncategorized alerts

  - name: 'critical-alerts'
    telegram_configs:
      - bot_token: '${TELEGRAM_BOT_TOKEN}'
        chat_id: ${TELEGRAM_CHAT_ID}
        message: '{{ template "telegram.critical" . }}'
        parse_mode: 'HTML'

  - name: 'warning-alerts'
    telegram_configs:
      - bot_token: '${TELEGRAM_BOT_TOKEN}'
        chat_id: ${TELEGRAM_CHAT_ID}
        message: '{{ template "telegram.warning" . }}'
        parse_mode: 'HTML'

# Inhibition rules to prevent spam
inhibit_rules:
  # Inhibit warning alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']