# Mapping Rules Configuration
# Define how Jira Tempo projects/issues map to Solidtime projects/tasks

project_mappings:
  # Jira Project Key -> Solidtime Project Name/ID
  # Example: "PROJ": "My Project Name"
  {}

task_mappings:
  # Based on issue type, labels, or specific patterns
  issue_types:
    "Story": "Development"
    "Bug": "Bug Fixing"
    "Task": "General Tasks"
    "Sub-task": "Development"

  # Label-based mappings (if issue has specific labels)
  labels:
    "meeting": "Meetings"
    "review": "Code Review"
    "deployment": "DevOps"
    "research": "Research"

  # Fallback task name
  default: "General Work"

# Field mappings
field_mappings:
  # How to handle billable status
  billable_rules:
    # If Tempo worklog has billableSeconds > 0, mark as billable
    default: "auto"  # auto, always_billable, never_billable

    # Override by project
    overrides:
      "ADMIN": "never_billable"
      "CLIENT": "always_billable"

# Export settings
export:
  csv_columns:
    - date
    - start_time
    - duration_hours
    - project
    - task
    - description
    - billable
    - jira_issue_key

  date_format: "%Y-%m-%d"
  time_format: "%H:%M"