# Development Docker Compose with useful tools and debug capabilities

services:
  jira2solidtime:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: jira2solidtime-dev
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
      - ../config:/app/config
      - ../src:/app/src  # Mount source for development
    env_file: ../.env
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=DEBUG
    restart: "no"  # Don't restart in dev mode
    command: ["tail", "-f", "/dev/null"]  # Keep container running

  # Lightweight monitoring for development
  prometheus:
    image: prom/prometheus:latest
    container_name: jira2solidtime-prometheus-dev
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: jira2solidtime-grafana-dev
    ports:
      - "3000:3000"
    volumes:
      - ../monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ../monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped

networks:
  default:
    name: jira2solidtime-dev