# Minimal Docker Compose for jira2solidtime application only
# No monitoring services - for simple production deployment

services:
  jira2solidtime:
    image: cddsab/jira2solidtime:0.1.0-beta-app
    # Alternative: Build from source
    # build:
    #   context: ..
    #   dockerfile: docker/Dockerfile.app
    container_name: jira2solidtime-app
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    env_file: ../.env
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

    # Run sync on schedule using cron-like syntax
    labels:
      # Ofelia cron job configuration
      ofelia.enabled: "true"
      ofelia.job-exec.sync.schedule: "0 8 * * *"  # Daily at 8 AM
      ofelia.job-exec.sync.command: "jira2solidtime sync"

  # Lightweight scheduler for cron jobs
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: jira2solidtime-scheduler
    depends_on:
      - jira2solidtime
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

volumes:
  data:
    driver: local
  logs:
    driver: local