global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'jira2solidtime-metrics'
    scrape_interval: 30s
    static_configs:
      - targets: ['metrics-server:8000']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']